//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_ModulesFunctions", "ModulesFunctions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccess.ModulesFunctions), "AccessToModuleFunctions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.AccessToModuleFunctions))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_Roles", "Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccess.Roles), "AccessToModuleFunctions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.AccessToModuleFunctions))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_Users", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccess.Users), "AccessToModuleFunctions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.AccessToModuleFunctions))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AuthenticationDemoModel", "FK_ModulesFunctions_Functions", "Functions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Functions), "ModulesFunctions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.ModulesFunctions))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AuthenticationDemoModel", "FK_ModulesFunctions_Modules", "Modules", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Modules), "ModulesFunctions", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.ModulesFunctions))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("AuthenticationDemoModel", "FK_Users_Roles", "Roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccess.Roles), "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Users))]

// Original file name:
// Generation date: 13.11.2009 г. 20:47:10
namespace DataAccess
{
    
    /// <summary>
    /// There are no comments for AuthenticationDemoEntities in the schema.
    /// </summary>
    public partial class AuthenticationDemoEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new AuthenticationDemoEntities object using the connection string found in the 'AuthenticationDemoEntities' section of the application configuration file.
        /// </summary>
        public AuthenticationDemoEntities() : 
                base("name=AuthenticationDemoEntities", "AuthenticationDemoEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AuthenticationDemoEntities object.
        /// </summary>
        public AuthenticationDemoEntities(string connectionString) : 
                base(connectionString, "AuthenticationDemoEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new AuthenticationDemoEntities object.
        /// </summary>
        public AuthenticationDemoEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "AuthenticationDemoEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for AccessToModuleFunctions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AccessToModuleFunctions> AccessToModuleFunctions
        {
            get
            {
                if ((this._AccessToModuleFunctions == null))
                {
                    this._AccessToModuleFunctions = base.CreateQuery<AccessToModuleFunctions>("[AccessToModuleFunctions]");
                }
                return this._AccessToModuleFunctions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AccessToModuleFunctions> _AccessToModuleFunctions;
        /// <summary>
        /// There are no comments for Functions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Functions> Functions
        {
            get
            {
                if ((this._Functions == null))
                {
                    this._Functions = base.CreateQuery<Functions>("[Functions]");
                }
                return this._Functions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Functions> _Functions;
        /// <summary>
        /// There are no comments for Modules in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Modules> Modules
        {
            get
            {
                if ((this._Modules == null))
                {
                    this._Modules = base.CreateQuery<Modules>("[Modules]");
                }
                return this._Modules;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Modules> _Modules;
        /// <summary>
        /// There are no comments for ModulesFunctions in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ModulesFunctions> ModulesFunctions
        {
            get
            {
                if ((this._ModulesFunctions == null))
                {
                    this._ModulesFunctions = base.CreateQuery<ModulesFunctions>("[ModulesFunctions]");
                }
                return this._ModulesFunctions;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ModulesFunctions> _ModulesFunctions;
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Roles> Roles
        {
            get
            {
                if ((this._Roles == null))
                {
                    this._Roles = base.CreateQuery<Roles>("[Roles]");
                }
                return this._Roles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Roles> _Roles;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// There are no comments for AccessToModuleFunctions in the schema.
        /// </summary>
        public void AddToAccessToModuleFunctions(AccessToModuleFunctions accessToModuleFunctions)
        {
            base.AddObject("AccessToModuleFunctions", accessToModuleFunctions);
        }
        /// <summary>
        /// There are no comments for Functions in the schema.
        /// </summary>
        public void AddToFunctions(Functions functions)
        {
            base.AddObject("Functions", functions);
        }
        /// <summary>
        /// There are no comments for Modules in the schema.
        /// </summary>
        public void AddToModules(Modules modules)
        {
            base.AddObject("Modules", modules);
        }
        /// <summary>
        /// There are no comments for ModulesFunctions in the schema.
        /// </summary>
        public void AddToModulesFunctions(ModulesFunctions modulesFunctions)
        {
            base.AddObject("ModulesFunctions", modulesFunctions);
        }
        /// <summary>
        /// There are no comments for Roles in the schema.
        /// </summary>
        public void AddToRoles(Roles roles)
        {
            base.AddObject("Roles", roles);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    }
    /// <summary>
    /// There are no comments for AuthenticationDemoModel.AccessToModuleFunctions in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AuthenticationDemoModel", Name="AccessToModuleFunctions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AccessToModuleFunctions : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AccessToModuleFunctions object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static AccessToModuleFunctions CreateAccessToModuleFunctions(int id)
        {
            AccessToModuleFunctions accessToModuleFunctions = new AccessToModuleFunctions();
            accessToModuleFunctions.ID = id;
            return accessToModuleFunctions;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property HasAccess in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> HasAccess
        {
            get
            {
                return this._HasAccess;
            }
            set
            {
                this.OnHasAccessChanging(value);
                this.ReportPropertyChanging("HasAccess");
                this._HasAccess = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HasAccess");
                this.OnHasAccessChanged();
            }
        }
        private global::System.Nullable<bool> _HasAccess;
        partial void OnHasAccessChanging(global::System.Nullable<bool> value);
        partial void OnHasAccessChanged();
        /// <summary>
        /// There are no comments for ModulesFunctions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_ModulesFunctions", "ModulesFunctions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ModulesFunctions ModulesFunctions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ModulesFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_ModulesFunctions", "ModulesFunctions").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ModulesFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_ModulesFunctions", "ModulesFunctions").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ModulesFunctions in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ModulesFunctions> ModulesFunctionsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ModulesFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_ModulesFunctions", "ModulesFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ModulesFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_ModulesFunctions", "ModulesFunctions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_Roles", "Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Roles Role
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Roles>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Roles", "Roles").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Roles>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Roles", "Roles").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Roles> RoleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Roles>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Roles", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Roles>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Roles", "Roles", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_Users", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Users", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Users", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AuthenticationDemoModel.Functions in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AuthenticationDemoModel", Name="Functions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Functions : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Functions object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Functions CreateFunctions(int id, string name)
        {
            Functions functions = new Functions();
            functions.ID = id;
            functions.Name = name;
            return functions;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for ModulesFunctions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_ModulesFunctions_Functions", "ModulesFunctions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ModulesFunctions> ModulesFunctions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ModulesFunctions>("AuthenticationDemoModel.FK_ModulesFunctions_Functions", "ModulesFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ModulesFunctions>("AuthenticationDemoModel.FK_ModulesFunctions_Functions", "ModulesFunctions", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AuthenticationDemoModel.Modules in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AuthenticationDemoModel", Name="Modules")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Modules : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Modules object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Modules CreateModules(int id, string name)
        {
            Modules modules = new Modules();
            modules.ID = id;
            modules.Name = name;
            return modules;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for ModulesFunctions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_ModulesFunctions_Modules", "ModulesFunctions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ModulesFunctions> ModulesFunctions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ModulesFunctions>("AuthenticationDemoModel.FK_ModulesFunctions_Modules", "ModulesFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ModulesFunctions>("AuthenticationDemoModel.FK_ModulesFunctions_Modules", "ModulesFunctions", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AuthenticationDemoModel.ModulesFunctions in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AuthenticationDemoModel", Name="ModulesFunctions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ModulesFunctions : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ModulesFunctions object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static ModulesFunctions CreateModulesFunctions(int id)
        {
            ModulesFunctions modulesFunctions = new ModulesFunctions();
            modulesFunctions.ID = id;
            return modulesFunctions;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for AccessToModuleFunctions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_ModulesFunctions", "AccessToModuleFunctions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AccessToModuleFunctions> AccessToModuleFunctions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AccessToModuleFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_ModulesFunctions", "AccessToModuleFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AccessToModuleFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_ModulesFunctions", "AccessToModuleFunctions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Function in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_ModulesFunctions_Functions", "Functions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Functions Function
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Functions>("AuthenticationDemoModel.FK_ModulesFunctions_Functions", "Functions").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Functions>("AuthenticationDemoModel.FK_ModulesFunctions_Functions", "Functions").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Function in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Functions> FunctionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Functions>("AuthenticationDemoModel.FK_ModulesFunctions_Functions", "Functions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Functions>("AuthenticationDemoModel.FK_ModulesFunctions_Functions", "Functions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Module in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_ModulesFunctions_Modules", "Modules")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Modules Module
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Modules>("AuthenticationDemoModel.FK_ModulesFunctions_Modules", "Modules").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Modules>("AuthenticationDemoModel.FK_ModulesFunctions_Modules", "Modules").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Module in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Modules> ModuleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Modules>("AuthenticationDemoModel.FK_ModulesFunctions_Modules", "Modules");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Modules>("AuthenticationDemoModel.FK_ModulesFunctions_Modules", "Modules", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AuthenticationDemoModel.Roles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AuthenticationDemoModel", Name="Roles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Roles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Roles object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Roles CreateRoles(int id, string name)
        {
            Roles roles = new Roles();
            roles.ID = id;
            roles.Name = name;
            return roles;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for AccessToModuleFunctions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_Roles", "AccessToModuleFunctions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AccessToModuleFunctions> AccessToModuleFunctions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AccessToModuleFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Roles", "AccessToModuleFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AccessToModuleFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Roles", "AccessToModuleFunctions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_Users_Roles", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Users> Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Users>("AuthenticationDemoModel.FK_Users_Roles", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Users>("AuthenticationDemoModel.FK_Users_Roles", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for AuthenticationDemoModel.Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="AuthenticationDemoModel", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="hash">Initial value of Hash.</param>
        /// <param name="salt">Initial value of Salt.</param>
        public static Users CreateUsers(int id, string userName, string hash, string salt)
        {
            Users users = new Users();
            users.ID = id;
            users.UserName = userName;
            users.Hash = hash;
            users.Salt = salt;
            return users;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Hash in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash
        {
            get
            {
                return this._Hash;
            }
            set
            {
                this.OnHashChanging(value);
                this.ReportPropertyChanging("Hash");
                this._Hash = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Hash");
                this.OnHashChanged();
            }
        }
        private string _Hash;
        partial void OnHashChanging(string value);
        partial void OnHashChanged();
        /// <summary>
        /// There are no comments for Property Salt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Salt
        {
            get
            {
                return this._Salt;
            }
            set
            {
                this.OnSaltChanging(value);
                this.ReportPropertyChanging("Salt");
                this._Salt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Salt");
                this.OnSaltChanged();
            }
        }
        private string _Salt;
        partial void OnSaltChanging(string value);
        partial void OnSaltChanged();
        /// <summary>
        /// There are no comments for AccessToModuleFunctions in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_AccessToModuleFunctions_Users", "AccessToModuleFunctions")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AccessToModuleFunctions> AccessToModuleFunctions
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AccessToModuleFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Users", "AccessToModuleFunctions");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AccessToModuleFunctions>("AuthenticationDemoModel.FK_AccessToModuleFunctions_Users", "AccessToModuleFunctions", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("AuthenticationDemoModel", "FK_Users_Roles", "Roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Roles Role
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Roles>("AuthenticationDemoModel.FK_Users_Roles", "Roles").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Roles>("AuthenticationDemoModel.FK_Users_Roles", "Roles").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Roles> RoleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Roles>("AuthenticationDemoModel.FK_Users_Roles", "Roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Roles>("AuthenticationDemoModel.FK_Users_Roles", "Roles", value);
                }
            }
        }
    }
}
